---
- name: Patch Windows Systems
  hosts: windows
  gather_facts: yes

  tasks:
    - name: Set OS variable
      set_fact:
        os: "{{ ansible_facts.os_name | default('unknown') }}"

    - name: Show OS value
      debug:
        var: os

    - name: Patch Windows
      ansible.builtin.include_tasks: patch_windows.yml
      when: os is defined and (os is match(".*Windows.*") or os is match(".*2022.*"))
