- name: Install Windows Updates
  ansible.windows.win_updates:
    state: installed
    reboot: true
    reboot_timeout: 1800
    category_names:
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups
      - DefinitionUpdates
    server_selection: wua  # WSUS-safe mode
  register: patchresult

- name: Final Patch Summary
  ansible.builtin.debug:
    msg: |
      Host: {{ inventory_hostname }}
      OS: {{ ansible_facts.os_name | default('Windows') }} {{ ansible_facts.os_version | default('Unknown') }}
      {% set updates = patchresult.updates | default({}) | dict2items | map(attribute='value') | list %}
      {% set installed = updates | selectattr('kb','defined') | selectattr('installed','equalto',true) | map(attribute='kb') | list | flatten %}
      {% set failed = updates | selectattr('kb','defined') | selectattr('installed','equalto',false) | map(attribute='kb') | list | flatten %}
      Installed KBs: {{ installed if installed | length > 0 else 'None' }}
      Failed KBs: {{ failed if failed | length > 0 else 'None' }}
