- name: Install Windows Updates
  ansible.windows.win_updates:
    state: installed
    reboot: true
    reboot_timeout: 1800
    category_names:
      - CriticalUpdates
      - SecurityUpdates
      - UpdateRollups
      # - DefinitionUpdates   # Optional: may block other updates
    server_selection: auto   # Let Windows choose WSUS or Microsoft Update
  register: patchresult
  ignore_errors: yes

- name: Ensure host is rebooted if required
  ansible.windows.win_reboot:
    reboot_timeout: 1800
  when: patchresult.reboot_required | default(false)

- name: Final Patch Summary
  ansible.builtin.debug:
    msg: |
      Host: {{ inventory_hostname }}
      OS: {{ ansible_facts.os_name | default('Windows') }} {{ ansible_facts.os_version | default('Unknown') }}

      {% set updates = patchresult.updates | default([]) %}
      {% set installed = updates | selectattr('installed','equalto',true) | map(attribute='kb') | list %}
      {% set failed = updates | selectattr('installed','equalto',false) | map(attribute='kb') | list %}

      Installed KBs: {{ installed if installed | length > 0 else 'None' }}
      Failed KBs: {{ failed if failed | length > 0 else 'None' }}
      Reboot Required: {{ patchresult.reboot_required | default(false) }}
