- name: Start Windows Update Scan
  ansible.windows.win_updates:
    category_names: "{{ categories | default('*') }}"
    state: searched
  register: scanresult

- name: Show available updates
  ansible.builtin.debug:
    msg: >-
      {% if scanresult.updates | length > 0 %}
      Updates available:
      {% for update in scanresult.updates.values() %}
        - {{ update.title }}
      {% endfor %}
      {% else %}
      No updates found.
      {% endif %}

- name: Install Windows Updates (with reboot)
  ansible.windows.win_updates:
    category_names: "{{ categories | default('*') }}"
    reboot: true
  register: patchresult

- name: Show installation results
  ansible.builtin.debug:
    msg: >-
      {% set updates = patchresult.updates | default({}) %}
      {% if updates | length > 0 %}
      Installation results:
      {% for update in updates.values() %}
        - {{ update.title }} : {{ 'Installed' if update.installed else 'Failed' }}
      {% endfor %}
      {% else %}
      No updates were installed.
      {% endif %}
