- name: Install Windows Updates (robust)
  ansible.windows.win_updates:
    category_names: "{{ categories | default('*') }}"
    reboot: true
    accept_list: "{{ accept_packages | default(omit) }}"
    reject_list: "{{ reject_packages | default(omit) }}"
  register: patchresult
  ignore_errors: yes

- name: Show Installed KBs
  ansible.builtin.debug:
    msg: >-
      {% set kbs = patchresult.updates | default({}) 
         | dict2items 
         | map(attribute='value') 
         | selectattr('kb','defined') 
         | selectattr('installed','equalto',true) 
         | map(attribute='kb') 
         | list 
         | flatten %}
      {% if kbs | length > 0 %}
      Installed KBs:
      {% for kb in kbs %}
        - {{ kb }}
      {% endfor %}
      {% else %}
      No KBs installed.
      {% endif %}

- name: Show Failed KBs
  ansible.builtin.debug:
    msg: >-
      {% set failed_kbs = patchresult.updates | default({}) 
         | dict2items 
         | map(attribute='value') 
         | selectattr('kb','defined') 
         | selectattr('installed','equalto',false) 
         | map(attribute='kb') 
         | list 
         | flatten %}
      {% if failed_kbs | length > 0 %}
      Failed KBs:
      {% for kb in failed_kbs %}
        - {{ kb }}
      {% endfor %}
      {% else %}
      No failed KBs.
      {% endif %}
