---
#- name: Check for packages to include
  # ansible.builtin.set_fact:
    #   accept_packages: "{{ acceptlist.split(',') }}"
      # when: acceptlist is defined and acceptlist != ''

    #- name: Check for packages to exclude
  #ansible.builtin.set_fact:
    #reject_packages: "{{ rejectlist.split(',') }}"
      #when: rejectlist is defined and rejectlist != ''

    #- name: Install Windows Updates
  #  ansible.windows.win_updates:
    #   category_names: "{{ categories | default('*') }}"
      #    reboot: "{{ reboot_server | default(true) }}"
      #    accept_list: "{{ accept_packages | default(omit) }}"
      #    reject_list: "{{ reject_packages | default(omit) }}"
      #  register: patchresult

    #- name: Display Patching Results
  #  ansible.builtin.debug:
    #    msg: "{{ patchresult.updates.values() | map(attribute='title') | list }}"
- name: Deploy Windows Patches
  hosts: windows
  gather_facts: no
  tasks:
    - name: Check Windows Update Service Status
      win_service:
        name: wuauserv
      register: update_service_status
    - name: Start Windows Update Service if not running
      win_service:
        name: wuauserv
        start_mode: auto
        state: started
      when: update_service_status.state != "running"
    - name: Search and Install Windows Updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        reboot: yes
        state: installed
      register: update_result
