---
- name: Windows patching playbook
  hosts: windows

  roles:
    - shadowman_patching

  tasks:

    - name: Build the report
      ansible.builtin.include_role:
        name: build_report_windows_patch
        apply:
          delegate_to: 172.25.225.75
          run_once: true
